export const pizzas = [
  {
    id: 'margherita',
    name: 'Margherita',
    subtitle: 'La Clásica',
    description: 'Salsa de tomate San Marzano, mozzarella di bufala, albahaca fresca y aceite de oliva virgen extra.',
    ingredients: ['Tomate San Marzano', 'Mozzarella di Bufala', 'Albahaca Fresca', 'AOVE'],
    basePrice: 8500,
    sizes: [
      { name: 'Pequeña', price: 7200, inches: '10"' },
      { name: 'Mediana', price: 8500, inches: '12"' },
      { name: 'Grande', price: 9800, inches: '14"' },
    ],
    category: 'clasicas',
    image: 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/67261afd3_generated_d5e6bc74.png',
    spicy: false,
    vegetarian: true,
    stock: 40,
  },
  {
    id: 'pepperoni',
    name: 'Pepperoni',
    subtitle: 'Fuego & Carne',
    description: 'Pepperoni artesanal curado, mozzarella fundida, salsa de tomate casera y orégano.',
    ingredients: ['Pepperoni Artesanal', 'Mozzarella', 'Salsa de Tomate', 'Orégano'],
    basePrice: 9500,
    sizes: [
      { name: 'Pequeña', price: 8200, inches: '10"' },
      { name: 'Mediana', price: 9500, inches: '12"' },
      { name: 'Grande', price: 11000, inches: '14"' },
    ],
    category: 'clasicas',
    image: 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/e457bf323_generated_63cd8936.png',
    spicy: false,
    vegetarian: false,
    stock: 35,
  },
  {
    id: 'quattro-formaggi',
    name: 'Quattro Formaggi',
    subtitle: 'Cuatro Tesoros',
    description: 'Mozzarella, gorgonzola, parmesano y fontina. Un viaje por los quesos italianos.',
    ingredients: ['Mozzarella', 'Gorgonzola', 'Parmesano', 'Fontina'],
    basePrice: 10500,
    sizes: [
      { name: 'Pequeña', price: 9000, inches: '10"' },
      { name: 'Mediana', price: 10500, inches: '12"' },
      { name: 'Grande', price: 12000, inches: '14"' },
    ],
    category: 'especiales',
    image: 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/904a29c62_generated_d6b53e2c.png',
    spicy: false,
    vegetarian: true,
    stock: 25,
  },
  {
    id: 'prosciutto',
    name: 'Prosciutto e Rucola',
    subtitle: 'Eleganza Italiana',
    description: 'Prosciutto crudo de Parma, rúcula fresca, parmesano en lascas y mozzarella.',
    ingredients: ['Prosciutto di Parma', 'Rúcula', 'Parmesano', 'Mozzarella'],
    basePrice: 11500,
    sizes: [
      { name: 'Pequeña', price: 10000, inches: '10"' },
      { name: 'Mediana', price: 11500, inches: '12"' },
      { name: 'Grande', price: 13200, inches: '14"' },
    ],
    category: 'especiales',
    image: 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/72057cf4f_generated_b48edcb1.png',
    spicy: false,
    vegetarian: false,
    stock: 20,
  },
  {
    id: 'diavola',
    name: 'Diavola',
    subtitle: 'Pasión Picante',
    description: 'Salami picante, nduja calabresa, chile fresco, mozzarella y salsa de tomate con un toque de miel.',
    ingredients: ['Salami Picante', 'Nduja', 'Chile Fresco', 'Miel', 'Mozzarella'],
    basePrice: 10500,
    sizes: [
      { name: 'Pequeña', price: 9000, inches: '10"' },
      { name: 'Mediana', price: 10500, inches: '12"' },
      { name: 'Grande', price: 12000, inches: '14"' },
    ],
    category: 'especiales',
    image: 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/51bd77395_generated_d04f4879.png',
    spicy: true,
    vegetarian: false,
    stock: 30,
  },
  {
    id: 'vegetariana',
    name: 'Ortolana',
    subtitle: 'Del Huerto',
    description: 'Pimientos asados, calabacín, berenjena, alcachofas, aceitunas negras y mozzarella.',
    ingredients: ['Pimientos', 'Calabacín', 'Berenjena', 'Alcachofas', 'Aceitunas', 'Mozzarella'],
    basePrice: 9500,
    sizes: [
      { name: 'Pequeña', price: 8200, inches: '10"' },
      { name: 'Mediana', price: 9500, inches: '12"' },
      { name: 'Grande', price: 11000, inches: '14"' },
    ],
    category: 'clasicas',
    image: 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/b307305db_generated_02943b17.png',
    spicy: false,
    vegetarian: true,
    stock: 28,
  },
  {
    id: 'tartufo',
    name: 'Tartufo',
    subtitle: 'Lujo Negro',
    description: 'Setas silvestres, aceite de trufa negra, mozzarella, parmesano y tomillo fresco.',
    ingredients: ['Setas Silvestres', 'Trufa Negra', 'Mozzarella', 'Parmesano', 'Tomillo'],
    basePrice: 13500,
    sizes: [
      { name: 'Pequeña', price: 11800, inches: '10"' },
      { name: 'Mediana', price: 13500, inches: '12"' },
      { name: 'Grande', price: 15200, inches: '14"' },
    ],
    category: 'especiales',
    image: 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/950903746_generated_9c87e596.png',
    spicy: false,
    vegetarian: true,
    stock: 15,
  },
];

export const categories = [
  { id: 'todas', label: 'Todas' },
  { id: 'clasicas', label: 'Clásicas' },
  { id: 'especiales', label: 'Especiales' },
];

export const heroImage = 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/433e23ca9_generated_11eac65c.png';
export const processImage = 'https://media.base44.com/images/public/6a2a2f4855a204e84179e053/8ff8090a6_generated_18f2eaeb.png';